stages:
  - analyze
  - test

analyze:
  stage: analyze
  tags:
    - build-flutter-3
  script:
    - flutter analyze
    - dart analyze --fatal-infos

test:
  stage: test
  tags:
    - build-flutter-3
  script:
    - flutter test test
