name: layer_sdk
description: A new Flutter package project.
version: 0.0.6

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # hosted
  biometrics_change_detector:
    git:
      url: git@gitlab.ubanquity.com:dart-packages/biometricts_change_detector.git
      ref: 3a0c7fdf8e602778265e1b284a25e6451bb1d426

  carrier_info:
    git:
      url: git@gitlab.ubanquity.com:flutter-apps/carrier-info.git
      ref: 433beda7e4b7c0249c9877fe09c9bbc4058fee27

  design_kit_layer:
    git:
      url: git@gitlab.ubanquity.com:dart-packages/design-kit-layer.git
      ref: 1d8576ecb785346cf1af88dda37253583b6520a6

  ocra_authentication:
    git:
      url: git@gitlab.ubanquity.com:dart-packages/ocra_authentication.git
      ref: 3994518ffff10e0dfb9b1864e4d18a3802a8758f

  # The MeaWallet SDK plugin
  # Possible branches:
  # - meawallet-prod  => Production SDK
  # - meawallet-test => Test SDK
  meawallet_plugin:
    git:
      url: git@gitlab.ubanquity.com:dart-packages/meawallet.git
      ref: meawallet-prod

  # pub.dev packages
  asn1lib: ^1.0.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.1.0
  collection: ^1.15.0
  contacts_service: ^0.6.3
  country_pickers: ^2.0.0
  device_info: ^2.0.2
  dio: ^4.0.4
  equatable: ^2.0.2
  file_picker: 4.2.6
  firebase_analytics: ^9.3.3
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.1
  firebase_messaging_platform_interface: 4.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_jailbreak_detection: ^1.8.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_local_notifications: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^1.1.0
  google_fonts: 2.2.0
  image: ^3.1.3
  image_cropper: ^2.0.3
  image_picker: ^0.8.4+6
  intl: ^0.17.0
  local_auth: ^2.1.0
  location: ^4.2.2
  logging: ^1.0.1
  mime: ^1.0.0
  open_file: ^3.2.1
  open_mail_app: ^0.2.0
  package_info: ^2.0.2
  path_provider: ^2.0.5
  permission_handler: ^8.2.5
  pointycastle: ^3.0.1
  shared_preferences: ^2.0.6
  uni_links: ^0.5.1
  url_launcher: ^6.1.0
  validators: ^3.0.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  # Keep this section alphabetized
  bloc_test: ^8.0.2
  effective_dart: ^1.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  test: ^1.17.5

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
