import '../../models.dart';

/// The default [Branding] with the Layer colors and fonts.
class LayerBranding extends Branding {
  /// Creates a new [LayerBranding]
  const LayerBranding()
      : super(
          defaultFontFamily: 'Inter',
          lightColors: const BrandingColors(
            brandGradientStart: 0xFFD40000,
            brandGradientEnd: 0xFFA30000,
            brandPrimary: 0xFFD40000,
            brandSecondary: 0xFFF21818,
            brandTertiary: 0xFFA30000,
            basePrimary: 0xFF1A1A1A,
            basePrimaryWhite: 0xFFFFFFFF,
            basePrimaryBlack: 0xFF1A1A1A,
            basePrimaryTertiary: 0xFF4D4D4D,
            basePrimaryQuinary: 0xFFB0B0B0,
            basePrimarySenary: 0xFFDCDCDC,
            baseSecondary: 0xFF3B3B3B,
            baseTertiary: 0xFF606060,
            baseQuaternary: 0xFF878787,
            baseQuinary: 0xFFB0B0B0,
            baseSenary: 0xFFDCDCDC,
            baseSeptenary: 0xFFEDEDED,
            baseOctonary: 0xFFF7F7F7,
            baseNonary: 0xFFFFFFFF,
            surfaceSeptenary1: 0xFFEDEDED,
            surfaceSeptenary2: 0xFFEDEDED,
            surfaceSeptenary3: 0xFFEDEDED,
            surfaceSeptenary4: 0xFFEDEDED,
            surfaceOctonary1: 0xFFF7F7F7,
            surfaceOctonary2: 0xFFF7F7F7,
            surfaceOctonary3: 0xFFF7F7F7,
            surfaceOctonary4: 0xFFF7F7F7,
            surfaceNonary1: 0xFFFFFFFF,
            surfaceNonary2: 0xFFFFFFFF,
            surfaceNonary3: 0xFFFFFFFF,
            surfaceNonary4: 0xFFFFFFFF,
            successAlpha: 0xFF06210B,
            successPrimary: 0xFF14B331,
            successDarkPrimary: 0xFF008732,
            successSecondary: 0xFF7ECF79,
            successTertiary: 0xFFE2F7DF,
            successQuaternary: 0xFFF9FFF7,
            successQuinary: 0xFFF9FFF7,
            errorAlpha: 0xFF2E0509,
            errorPrimary: 0xFFFF3347,
            errorDarkPrimary: 0xFFC9001E,
            errorSecondary: 0xFFFB867A,
            errorTertiary: 0xFFFFE8E5,
            errorQuaternary: 0xFFFFF8F7,
            errorQuinary: 0xFFFFF8F7,
            warningAlpha: 0xFF2D1605,
            warningPrimary: 0xFFFF791A,
            warningDarkPrimary: 0xFFD15400,
            warningSecondary: 0xFFFFAB73,
            warningTertiary: 0xFFFFF0E5,
            warningQuaternary: 0xFFFFFAF7,
            warningQuinary: 0xFFFFFAF7,
            cautionAlpha: 0xFF2C2102,
            cautionPrimary: 0xFFF5B907,
            cautionDarkPrimary: 0xFFCC8800,
            cautionSecondary: 0xFFFFD787,
            cautionTertiary: 0xFFFFF3D9,
            cautionQuaternary: 0xFFFFFCF7,
            cautionQuinary: 0xFFFFFCF7,
            infoAlpha: 0xFF09182A,
            infoDarkPrimary: 0xFF0068BD,
            infoPrimary: 0xFF2787F5,
            infoSecondary: 0xFF8BADF9,
            infoTertiary: 0xFFE4EAFD,
            infoQuaternary: 0xFFF7F8FF,
            infoQuinary: 0xFFF7F8FF,
          ),
          darkColors: const BrandingColors(
            brandGradientStart: 0xFFE01616,
            brandGradientEnd: 0xFFB01212,
            brandPrimary: 0xFFE01616,
            brandSecondary: 0xFFF52222,
            brandTertiary: 0xFFB01212,
            basePrimary: 0xFFF2F2F2,
            basePrimaryWhite: 0xFFF2F2F2,
            basePrimaryBlack: 0xFF1A1A1A,
            basePrimaryTertiary: 0xFF4D4D4D,
            basePrimaryQuinary: 0xFFB0B0B0,
            basePrimarySenary: 0xFFDCDCDC,
            baseSecondary: 0xFFC6C6C6,
            baseTertiary: 0xFF9B9B9B,
            baseQuaternary: 0xFF737373,
            baseQuinary: 0xFF4D4D4D,
            baseSenary: 0xFF2A2A2A,
            baseSeptenary: 0xFF1F1F1F,
            baseOctonary: 0xFF181818,
            baseNonary: 0xFF0D0D0D,
            surfaceSeptenary1: 0xFF0D0D0D,
            surfaceSeptenary2: 0xFF181818,
            surfaceSeptenary3: 0xFF1F1F1F,
            surfaceSeptenary4: 0xFF2A2A2A,
            surfaceOctonary1: 0xFF0D0D0D,
            surfaceOctonary2: 0xFF181818,
            surfaceOctonary3: 0xFF1F1F1F,
            surfaceOctonary4: 0xFF2A2A2A,
            surfaceNonary1: 0xFF0D0D0D,
            surfaceNonary2: 0xFF181818,
            surfaceNonary3: 0xFF1F1F1F,
            surfaceNonary4: 0xFF2A2A2A,
            successAlpha: 0xFF06210B,
            successPrimary: 0xFF28BF44,
            successDarkPrimary: 0xFF4BFA77,
            successSecondary: 0xFF2A7E33,
            successTertiary: 0xFF214321,
            successQuaternary: 0xFF202E1F,
            successQuinary: 0xFFF9FFF7,
            errorAlpha: 0xFF2E0509,
            errorPrimary: 0xFFFF2B4F,
            errorDarkPrimary: 0xFFFF5266,
            errorSecondary: 0xFFA73B42,
            errorTertiary: 0xFF572627,
            errorQuaternary: 0xFF301B1B,
            errorQuinary: 0xFFFFF8F7,
            warningAlpha: 0xFF2D1605,
            warningPrimary: 0xFFFF8833,
            warningDarkPrimary: 0xFFFF984F,
            warningSecondary: 0xFFA75C29,
            warningTertiary: 0xFF57341D,
            warningQuaternary: 0xFF332216,
            warningQuinary: 0xFFFFFAF7,
            cautionAlpha: 0xFF2C2102,
            cautionPrimary: 0xFFFFC926,
            cautionDarkPrimary: 0xFFFFD54A,
            cautionSecondary: 0xFFA78425,
            cautionTertiary: 0xFF56451D,
            cautionQuaternary: 0xFF302715,
            cautionQuinary: 0xFFFFFCF7,
            infoAlpha: 0xFF09182A,
            infoPrimary: 0xFF4094F5,
            infoDarkPrimary: 0xFF75BCFF,
            infoSecondary: 0xFF37639F,
            infoTertiary: 0xFF263652,
            infoQuaternary: 0xFF1F2638,
            infoQuinary: 0xFFF7F8FF,
          ),
          fonts: const BrandingFonts(
            baseTitleXXXL: BrandingFont(
              size: 32.0,
              weight: 600,
              lineHeight: 36.0,
              letterSpacingPercentage: -1.0,
            ),
            baseTitleXXL: BrandingFont(
              size: 24.0,
              weight: 600,
              lineHeight: 32.0,
              letterSpacingPercentage: -0.5,
            ),
            baseTitleXL: BrandingFont(
              size: 20.0,
              weight: 600,
              lineHeight: 28.0,
              letterSpacingPercentage: -0.25,
            ),
            baseTitleL: BrandingFont(
              size: 18.0,
              weight: 600,
              lineHeight: 24.0,
              letterSpacingPercentage: 0.0,
            ),
            baseTitleM: BrandingFont(
              size: 16.0,
              weight: 500,
              lineHeight: 24.0,
              letterSpacingPercentage: 0.0,
            ),
            baseTitleS: BrandingFont(
              size: 14.0,
              weight: 500,
              lineHeight: 20.0,
              letterSpacingPercentage: 1.0,
            ),
            baseTitleXS: BrandingFont(
              size: 12.0,
              weight: 500,
              lineHeight: 16.0,
              letterSpacingPercentage: 2.0,
            ),
            baseBodyXXL: BrandingFont(
              size: 24.0,
              weight: 400,
              lineHeight: 32.0,
              letterSpacingPercentage: -0.5,
            ),
            baseBodyXL: BrandingFont(
              size: 20.0,
              weight: 400,
              lineHeight: 28.0,
              letterSpacingPercentage: -0.25,
            ),
            baseBodyL: BrandingFont(
              size: 18.0,
              weight: 400,
              lineHeight: 24.0,
              letterSpacingPercentage: -0.15,
            ),
            baseBodyM: BrandingFont(
              size: 16.0,
              weight: 400,
              lineHeight: 24.0,
              letterSpacingPercentage: 0.0,
            ),
            baseBodyS: BrandingFont(
              size: 14.0,
              weight: 400,
              lineHeight: 20.0,
              letterSpacingPercentage: 0.0,
            ),
            baseBodyXS: BrandingFont(
              size: 12.0,
              weight: 400,
              lineHeight: 16.0,
              letterSpacingPercentage: 1.0,
            ),
            baseButtonM: BrandingFont(
              size: 16.0,
              weight: 500,
              lineHeight: 24.0,
              letterSpacingPercentage: 0.0,
            ),
            baseButtonS: BrandingFont(
              size: 14.0,
              weight: 500,
              lineHeight: 20.0,
              letterSpacingPercentage: 1.0,
            ),
          ),
        );
}
