library abstract_repositories;

export 'abstract_repositories/account/account_repository_interface.dart';
export 'abstract_repositories/account_loan/account_loan_repository_interface.dart';
export 'abstract_repositories/account_transaction/account_transaction_repository_interface.dart';
export 'abstract_repositories/cashback_history/cashback_history_repository_interface.dart';
export 'abstract_repositories/offers/offers_repository_interface.dart';
